<?xml version="1.0"?>
<robot name="gazebo_rgbd" xmlns:xacro="http://www.ros.org/wiki/xacro" xmlns:gz="http://gazebosim.org/schema">

<!--
Gazebo plugins can only be included once so this xacro assumes that a parent will include and configure them.
This xacro requires Gazebo plugin:
  - gz::sim::systems::Sensors
  to publish simulated RGBD camera data

For example:
<gazebo>
  <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
    <render_engine>ogre2</render_engine>
  </plugin>
</gazebo>
-->
<xacro:macro name="gazebo_rgbd" params="
  name:=camera
  fps:=15
  gz_topic_name:=camera
  image_width:=1280
  image_height:=720
  h_fov
  v_fov
  min_depth
  max_depth">

    <!--
    Assumptions:
    Simulated RGB and Depth sensors are in the same location as the RGB sensor of the physical camera.
    Simulated RGB and Depth sensors and have the same FOV as the RGB physical sensor.
    Note: physical hardware publishes pointcloud in `camera_depth_optical_frame` where this sensor will use
    the referenced camera color_frame. -->
    <xacro:property name="fx" value="${image_width * 0.5 / tan(h_fov * 0.5)}" />
    <xacro:property name="fy" value="${image_height * 0.5 / tan(v_fov * 0.5)}" />
    <xacro:property name="cx" value="${image_width * 0.5}" />
    <xacro:property name="cy" value="${image_height * 0.5}" />
    <xacro:property name="min_depth" value="0.52" />
    <xacro:property name="max_depth" value="6.0" />

    <gazebo reference="${name}_color_frame">
        <sensor name="${name}" type="rgbd_camera">
            <camera>
                <horizontal_fov>${h_fov}</horizontal_fov>
                <image>
                    <width>${image_width}</width>
                    <height>${image_height}</height>
                    <format>RGB_INT8</format>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>10</far>
                </clip>
                <distortion>
                    <k1>0.0</k1>
                    <k2>0.0</k2>
                    <k3>0.0</k3>
                    <p1>0.0</p1>
                    <p2>0.0</p2>
                    <center>0.5 0.5</center>
                </distortion>
                <lens>
                    <intrinsics>
                        <fx>${fx}</fx>
                        <fy>${fy}</fy>
                        <cx>${cx}</cx>
                        <cy>${cy}</cy>
                        <s>0</s>
                    </intrinsics>
                    <projection>
                        <p_fx>${fx}</p_fx>
                        <p_fy>${fy}</p_fy>
                        <p_cx>${cx}</p_cx>
                        <p_cy>${cy}</p_cy>
                        <tx>0</tx>
                        <ty>0</ty>
                    </projection>
                </lens>
                <noise>
                    <type>gaussian</type>
                    <mean>0</mean>
                    <stddev>0.00</stddev>
                </noise>
                <depth_camera>
                    <clip>
                        <near>${min_depth}</near>
                        <far>${max_depth}</far>
                    </clip>
                </depth_camera>
                <optical_frame_id>${name}_color_optical_frame</optical_frame_id>
            </camera>
            <gz_frame_id>${name}_color_frame</gz_frame_id>
            <always_on>1</always_on>
            <update_rate>${fps}</update_rate>
            <visualize>false</visualize>
            <topic>${gz_topic_name}</topic>
            <enable_metrics>false</enable_metrics>
        </sensor>
    </gazebo>

</xacro:macro>
</robot>
